#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 12 20:02:50 CEST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_memory_behav -key {Behavioral:sim_1:Functional:test_memory} -tclbatch test_memory.tcl -log simulate.log"
xsim test_memory_behav -key {Behavioral:sim_1:Functional:test_memory} -tclbatch test_memory.tcl -log simulate.log

